// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/WillieBam/support_copilot/backend/types"
)

// IAppService is an autogenerated mock type for the IAppService type
type IAppService struct {
	mock.Mock
}

// QueryStream provides a mock function with given fields: ctx, prompt, streamChan
func (_m *IAppService) QueryStream(ctx context.Context, prompt string, streamChan chan<- types.StreamEvent) error {
	ret := _m.Called(ctx, prompt, streamChan)

	if len(ret) == 0 {
		panic("no return value specified for QueryStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, chan<- types.StreamEvent) error); ok {
		r0 = rf(ctx, prompt, streamChan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAppService creates a new instance of IAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAppService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAppService {
	mock := &IAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
