// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/WillieBam/support_copilot/backend/types/models"

	types "github.com/WillieBam/support_copilot/backend/types"

	uuid "github.com/google/uuid"
)

// IAppService is an autogenerated mock type for the IAppService type
type IAppService struct {
	mock.Mock
}

// IngestAlert provides a mock function with given fields: ctx, incidentID, serviceName, severity, metrics
func (_m *IAppService) IngestAlert(ctx context.Context, incidentID uuid.UUID, serviceName string, severity string, metrics string) error {
	ret := _m.Called(ctx, incidentID, serviceName, severity, metrics)

	if len(ret) == 0 {
		panic("no return value specified for IngestAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r0 = rf(ctx, incidentID, serviceName, severity, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}


// QueryStreamWithTools provides a mock function with given fields: ctx, prompt, streamChan
func (_m *IAppService) QueryStreamWithTools(ctx context.Context, prompt string, streamChan chan<- types.StreamEvent) error {
	ret := _m.Called(ctx, prompt, streamChan)

	if len(ret) == 0 {
		panic("no return value specified for QueryStreamWithTools")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, chan<- types.StreamEvent) error); ok {
		r0 = rf(ctx, prompt, streamChan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveAlert provides a mock function with given fields: ctx, id
func (_m *IAppService) RetrieveAlert(ctx context.Context, id uuid.UUID) (*models.Alert, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAlert")
	}

	var r0 *models.Alert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Alert, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Alert); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Alert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAppService creates a new instance of IAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAppService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAppService {
	mock := &IAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
