// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/WillieBam/support_copilot/backend/types"
)

// IAuthService is an autogenerated mock type for the IAuthService type
type IAuthService struct {
	mock.Mock
}

// ExchangeToken provides a mock function with given fields: ctx, firebaseToken
func (_m *IAuthService) ExchangeToken(ctx context.Context, firebaseToken string) (string, *types.Claims, error) {
	ret := _m.Called(ctx, firebaseToken)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeToken")
	}

	var r0 string
	var r1 *types.Claims
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, *types.Claims, error)); ok {
		return rf(ctx, firebaseToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, firebaseToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *types.Claims); ok {
		r1 = rf(ctx, firebaseToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Claims)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, firebaseToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ParseAndValidateAuthToken provides a mock function with given fields: ctx, tokenString
func (_m *IAuthService) ParseAndValidateAuthToken(ctx context.Context, tokenString string) (*types.Claims, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseAndValidateAuthToken")
	}

	var r0 *types.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*types.Claims, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *types.Claims); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAuthService creates a new instance of IAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthService {
	mock := &IAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
