package mocks

import (
	context "context"

	types "github.com/WillieBam/support_copilot/backend/types"
	mock "github.com/stretchr/testify/mock"
)

// ICommandInterceptor is an autogenerated mock type for the ICommandInterceptor type
type ICommandInterceptor struct {
	mock.Mock
}

// Intercept provides a mock function with given fields: ctx, prompt
func (_m *ICommandInterceptor) Intercept(ctx context.Context, prompt string) (*types.CommandResult, error) {
	ret := _m.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Intercept")
	}

	var r0 *types.CommandResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*types.CommandResult, error)); ok {
		return rf(ctx, prompt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *types.CommandResult); ok {
		r0 = rf(ctx, prompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.CommandResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICommandInterceptor creates a new instance of ICommandInterceptor.
func NewICommandInterceptor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICommandInterceptor {
	mock := &ICommandInterceptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
