// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "firebase.google.com/go/v4/auth"

	mock "github.com/stretchr/testify/mock"
)

// IFirebaseRepository is an autogenerated mock type for the IFirebaseRepository type
type IFirebaseRepository struct {
	mock.Mock
}

// VerifyIDToken provides a mock function with given fields: ctx, idToken
func (_m *IFirebaseRepository) VerifyIDToken(ctx context.Context, idToken string) (*auth.Token, error) {
	ret := _m.Called(ctx, idToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyIDToken")
	}

	var r0 *auth.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.Token, error)); ok {
		return rf(ctx, idToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.Token); ok {
		r0 = rf(ctx, idToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIFirebaseRepository creates a new instance of IFirebaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIFirebaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IFirebaseRepository {
	mock := &IFirebaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
