package mocks

import (
	"github.com/WillieBam/support_copilot/backend/internal/classifier"
	mock "github.com/stretchr/testify/mock"
)

// IIntentClassifier is an autogenerated mock type for the IIntentClassifier interface.
type IIntentClassifier struct {
	mock.Mock
}

// Classify provides a mock function with given fields: prompt
func (_m *IIntentClassifier) Classify(prompt string) classifier.Intent {
	ret := _m.Called(prompt)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	return ret.Get(0).(classifier.Intent)
}

// NewIIntentClassifier creates a new instance of IIntentClassifier and wires up
// test expectation assertion on cleanup.
func NewIIntentClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *IIntentClassifier {
	m := &IIntentClassifier{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}
