// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	classifier "github.com/WillieBam/support_copilot/backend/internal/classifier"

	mock "github.com/stretchr/testify/mock"
)

// IIntentClassifier is an autogenerated mock type for the IIntentClassifier type
type IIntentClassifier struct {
	mock.Mock
}

// Classify provides a mock function with given fields: prompt
func (_m *IIntentClassifier) Classify(prompt string) classifier.Intent {
	ret := _m.Called(prompt)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 classifier.Intent
	if rf, ok := ret.Get(0).(func(string) classifier.Intent); ok {
		r0 = rf(prompt)
	} else {
		r0 = ret.Get(0).(classifier.Intent)
	}

	return r0
}

// NewIIntentClassifier creates a new instance of IIntentClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIIntentClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *IIntentClassifier {
	mock := &IIntentClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
