// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	requests "github.com/WillieBam/support_copilot/backend/types/requests"
)

// IMCPClient is an autogenerated mock type for the IMCPClient type
type IMCPClient struct {
	mock.Mock
}

// DetectAnomalies provides a mock function with given fields: ctx, anomalyReq
func (_m *IMCPClient) DetectAnomalies(ctx context.Context, anomalyReq requests.AnomalyDetectionRequest) (*requests.AnomalyDetectionResponse, error) {
	ret := _m.Called(ctx, anomalyReq)

	if len(ret) == 0 {
		panic("no return value specified for DetectAnomalies")
	}

	var r0 *requests.AnomalyDetectionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.AnomalyDetectionRequest) (*requests.AnomalyDetectionResponse, error)); ok {
		return rf(ctx, anomalyReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.AnomalyDetectionRequest) *requests.AnomalyDetectionResponse); ok {
		r0 = rf(ctx, anomalyReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*requests.AnomalyDetectionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.AnomalyDetectionRequest) error); ok {
		r1 = rf(ctx, anomalyReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIMCPClient creates a new instance of IMCPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMCPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMCPClient {
	mock := &IMCPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
