// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	requests "github.com/WillieBam/support_copilot/backend/types/requests"

	types "github.com/WillieBam/support_copilot/backend/types"
)

// IOllamaClient is an autogenerated mock type for the IOllamaClient type
type IOllamaClient struct {
	mock.Mock
}

// QueryStreamWithTools provides a mock function with given fields: ctx, req, streamChan
func (_m *IOllamaClient) QueryStreamWithTools(ctx context.Context, req requests.OllamaChatRequest, streamChan chan<- types.StreamEvent) (*requests.OllamaMessage, error) {
	ret := _m.Called(ctx, req, streamChan)

	if len(ret) == 0 {
		panic("no return value specified for QueryStreamWithTools")
	}

	var r0 *requests.OllamaMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.OllamaChatRequest, chan<- types.StreamEvent) (*requests.OllamaMessage, error)); ok {
		return rf(ctx, req, streamChan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, requests.OllamaChatRequest, chan<- types.StreamEvent) *requests.OllamaMessage); ok {
		r0 = rf(ctx, req, streamChan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*requests.OllamaMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, requests.OllamaChatRequest, chan<- types.StreamEvent) error); ok {
		r1 = rf(ctx, req, streamChan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOllamaClient creates a new instance of IOllamaClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOllamaClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOllamaClient {
	mock := &IOllamaClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
