// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	responses "github.com/WillieBam/support_copilot/backend/types/responses"

	uuid "github.com/google/uuid"
)

// IOrchestratorService is an autogenerated mock type for the IOrchestratorService type
type IOrchestratorService struct {
	mock.Mock
}

// ExecuteValidateAlert provides a mock function with given fields: ctx, alertID
func (_m *IOrchestratorService) ExecuteValidateAlert(ctx context.Context, alertID uuid.UUID) (*responses.CombinedValidationResult, error) {
	ret := _m.Called(ctx, alertID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteValidateAlert")
	}

	var r0 *responses.CombinedValidationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*responses.CombinedValidationResult, error)); ok {
		return rf(ctx, alertID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *responses.CombinedValidationResult); ok {
		r0 = rf(ctx, alertID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.CombinedValidationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, alertID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecuteValidateAlertRaw provides a mock function with given fields: ctx, rawArgs
func (_m *IOrchestratorService) ExecuteValidateAlertRaw(ctx context.Context, rawArgs string) (string, error) {
	ret := _m.Called(ctx, rawArgs)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteValidateAlertRaw")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, rawArgs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, rawArgs)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rawArgs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOrchestratorService creates a new instance of IOrchestratorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrchestratorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrchestratorService {
	mock := &IOrchestratorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
