// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	requests "github.com/WillieBam/support_copilot/backend/types/requests"
)

// IToolRegistry is an autogenerated mock type for the IToolRegistry type
type IToolRegistry struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, name, rawArgs
func (_m *IToolRegistry) Execute(ctx context.Context, name string, rawArgs string) (string, error) {
	ret := _m.Called(ctx, name, rawArgs)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, name, rawArgs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, name, rawArgs)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, rawArgs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTools provides a mock function with no fields
func (_m *IToolRegistry) GetTools() []requests.OllamaTool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTools")
	}

	var r0 []requests.OllamaTool
	if rf, ok := ret.Get(0).(func() []requests.OllamaTool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]requests.OllamaTool)
		}
	}

	return r0
}

// NewIToolRegistry creates a new instance of IToolRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIToolRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *IToolRegistry {
	mock := &IToolRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
